#语言配置 需重启
#language configuration, restart server
#zh_CN、zh_FT、en_US
lang: zh_CN

#mysql数据库支持 需重启
#mysql database support, restart server
mysql:
  enable: flase
  ip: localhost
  port: 3306
  user: root
  password: 123456
  database: lwlib
  table: lw_
