name: LWMcScaffold
author: LW-MrWU

website: http://www.gameclub.vip
description: LWMcScaffold is a scaffold service

main: com.gameclub.service.basic.service.plugin.MainPlugin
version: 1.0
api-version: 1.16

load: startup
database: false
